/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
var label_label_message_pb = require('../label/label_message_pb.js');
var class_class_message_pb = require('../class/class_message_pb.js');
goog.exportSymbol('proto.test.ExposeRankType', null, global);
goog.exportSymbol('proto.test.OverallTestScore', null, global);
goog.exportSymbol('proto.test.Test', null, global);
goog.exportSymbol('proto.test.TestExpectedGrade', null, global);
goog.exportSymbol('proto.test.TestScore', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.test.Test = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.test.Test.repeatedFields_, null);
};
goog.inherits(proto.test.Test, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.test.Test.displayName = 'proto.test.Test';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.test.Test.repeatedFields_ = [18,19];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.test.Test.prototype.toObject = function(opt_includeInstance) {
  return proto.test.Test.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.test.Test} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.test.Test.toObject = function(includeInstance, msg) {
  var f, obj = {
    uid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    createdAt: (f = msg.getCreatedAt()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    updatedAt: (f = msg.getUpdatedAt()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    classUid: jspb.Message.getFieldWithDefault(msg, 4, ""),
    name: jspb.Message.getFieldWithDefault(msg, 5, ""),
    description: jspb.Message.getFieldWithDefault(msg, 6, ""),
    round: jspb.Message.getFieldWithDefault(msg, 7, 0),
    average: +jspb.Message.getFieldWithDefault(msg, 8, 0.0),
    stDev: +jspb.Message.getFieldWithDefault(msg, 9, 0.0),
    highScore: +jspb.Message.getFieldWithDefault(msg, 10, 0.0),
    lowScore: +jspb.Message.getFieldWithDefault(msg, 11, 0.0),
    testLabel: (f = msg.getTestLabel()) && label_label_message_pb.Label.toObject(includeInstance, f),
    exposeRankType: jspb.Message.getFieldWithDefault(msg, 13, 0),
    startAt: (f = msg.getStartAt()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    endAt: (f = msg.getEndAt()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    closedAt: (f = msg.getClosedAt()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    publicExposedAt: (f = msg.getPublicExposedAt()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    scoresList: jspb.Message.toObjectList(msg.getScoresList(),
    proto.test.TestScore.toObject, includeInstance),
    expectedGradesList: jspb.Message.toObjectList(msg.getExpectedGradesList(),
    proto.test.TestExpectedGrade.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.test.Test}
 */
proto.test.Test.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.test.Test;
  return proto.test.Test.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.test.Test} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.test.Test}
 */
proto.test.Test.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setUid(value);
      break;
    case 2:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setCreatedAt(value);
      break;
    case 3:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setUpdatedAt(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setClassUid(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescription(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setRound(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setAverage(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setStDev(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setHighScore(value);
      break;
    case 11:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setLowScore(value);
      break;
    case 12:
      var value = new label_label_message_pb.Label;
      reader.readMessage(value,label_label_message_pb.Label.deserializeBinaryFromReader);
      msg.setTestLabel(value);
      break;
    case 13:
      var value = /** @type {!proto.test.ExposeRankType} */ (reader.readEnum());
      msg.setExposeRankType(value);
      break;
    case 14:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setStartAt(value);
      break;
    case 15:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setEndAt(value);
      break;
    case 16:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setClosedAt(value);
      break;
    case 17:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setPublicExposedAt(value);
      break;
    case 18:
      var value = new proto.test.TestScore;
      reader.readMessage(value,proto.test.TestScore.deserializeBinaryFromReader);
      msg.addScores(value);
      break;
    case 19:
      var value = new proto.test.TestExpectedGrade;
      reader.readMessage(value,proto.test.TestExpectedGrade.deserializeBinaryFromReader);
      msg.addExpectedGrades(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.test.Test.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.test.Test.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.test.Test} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.test.Test.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getCreatedAt();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getUpdatedAt();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getClassUid();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getDescription();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getRound();
  if (f !== 0) {
    writer.writeInt64(
      7,
      f
    );
  }
  f = message.getAverage();
  if (f !== 0.0) {
    writer.writeDouble(
      8,
      f
    );
  }
  f = message.getStDev();
  if (f !== 0.0) {
    writer.writeDouble(
      9,
      f
    );
  }
  f = message.getHighScore();
  if (f !== 0.0) {
    writer.writeDouble(
      10,
      f
    );
  }
  f = message.getLowScore();
  if (f !== 0.0) {
    writer.writeDouble(
      11,
      f
    );
  }
  f = message.getTestLabel();
  if (f != null) {
    writer.writeMessage(
      12,
      f,
      label_label_message_pb.Label.serializeBinaryToWriter
    );
  }
  f = message.getExposeRankType();
  if (f !== 0.0) {
    writer.writeEnum(
      13,
      f
    );
  }
  f = message.getStartAt();
  if (f != null) {
    writer.writeMessage(
      14,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getEndAt();
  if (f != null) {
    writer.writeMessage(
      15,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getClosedAt();
  if (f != null) {
    writer.writeMessage(
      16,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getPublicExposedAt();
  if (f != null) {
    writer.writeMessage(
      17,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getScoresList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      18,
      f,
      proto.test.TestScore.serializeBinaryToWriter
    );
  }
  f = message.getExpectedGradesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      19,
      f,
      proto.test.TestExpectedGrade.serializeBinaryToWriter
    );
  }
};


/**
 * optional string uid = 1;
 * @return {string}
 */
proto.test.Test.prototype.getUid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.test.Test.prototype.setUid = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional google.protobuf.Timestamp created_at = 2;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.test.Test.prototype.getCreatedAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 2));
};


/** @param {?proto.google.protobuf.Timestamp|undefined} value */
proto.test.Test.prototype.setCreatedAt = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.test.Test.prototype.clearCreatedAt = function() {
  this.setCreatedAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.test.Test.prototype.hasCreatedAt = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional google.protobuf.Timestamp updated_at = 3;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.test.Test.prototype.getUpdatedAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 3));
};


/** @param {?proto.google.protobuf.Timestamp|undefined} value */
proto.test.Test.prototype.setUpdatedAt = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


proto.test.Test.prototype.clearUpdatedAt = function() {
  this.setUpdatedAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.test.Test.prototype.hasUpdatedAt = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional string class_uid = 4;
 * @return {string}
 */
proto.test.Test.prototype.getClassUid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.test.Test.prototype.setClassUid = function(value) {
  jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string name = 5;
 * @return {string}
 */
proto.test.Test.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/** @param {string} value */
proto.test.Test.prototype.setName = function(value) {
  jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string description = 6;
 * @return {string}
 */
proto.test.Test.prototype.getDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/** @param {string} value */
proto.test.Test.prototype.setDescription = function(value) {
  jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional int64 round = 7;
 * @return {number}
 */
proto.test.Test.prototype.getRound = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/** @param {number} value */
proto.test.Test.prototype.setRound = function(value) {
  jspb.Message.setProto3IntField(this, 7, value);
};


/**
 * optional double average = 8;
 * @return {number}
 */
proto.test.Test.prototype.getAverage = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 8, 0.0));
};


/** @param {number} value */
proto.test.Test.prototype.setAverage = function(value) {
  jspb.Message.setProto3FloatField(this, 8, value);
};


/**
 * optional double st_dev = 9;
 * @return {number}
 */
proto.test.Test.prototype.getStDev = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 9, 0.0));
};


/** @param {number} value */
proto.test.Test.prototype.setStDev = function(value) {
  jspb.Message.setProto3FloatField(this, 9, value);
};


/**
 * optional double high_score = 10;
 * @return {number}
 */
proto.test.Test.prototype.getHighScore = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 10, 0.0));
};


/** @param {number} value */
proto.test.Test.prototype.setHighScore = function(value) {
  jspb.Message.setProto3FloatField(this, 10, value);
};


/**
 * optional double low_score = 11;
 * @return {number}
 */
proto.test.Test.prototype.getLowScore = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 11, 0.0));
};


/** @param {number} value */
proto.test.Test.prototype.setLowScore = function(value) {
  jspb.Message.setProto3FloatField(this, 11, value);
};


/**
 * optional label.Label test_label = 12;
 * @return {?proto.label.Label}
 */
proto.test.Test.prototype.getTestLabel = function() {
  return /** @type{?proto.label.Label} */ (
    jspb.Message.getWrapperField(this, label_label_message_pb.Label, 12));
};


/** @param {?proto.label.Label|undefined} value */
proto.test.Test.prototype.setTestLabel = function(value) {
  jspb.Message.setWrapperField(this, 12, value);
};


proto.test.Test.prototype.clearTestLabel = function() {
  this.setTestLabel(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.test.Test.prototype.hasTestLabel = function() {
  return jspb.Message.getField(this, 12) != null;
};


/**
 * optional ExposeRankType expose_rank_type = 13;
 * @return {!proto.test.ExposeRankType}
 */
proto.test.Test.prototype.getExposeRankType = function() {
  return /** @type {!proto.test.ExposeRankType} */ (jspb.Message.getFieldWithDefault(this, 13, 0));
};


/** @param {!proto.test.ExposeRankType} value */
proto.test.Test.prototype.setExposeRankType = function(value) {
  jspb.Message.setProto3EnumField(this, 13, value);
};


/**
 * optional google.protobuf.Timestamp start_at = 14;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.test.Test.prototype.getStartAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 14));
};


/** @param {?proto.google.protobuf.Timestamp|undefined} value */
proto.test.Test.prototype.setStartAt = function(value) {
  jspb.Message.setWrapperField(this, 14, value);
};


proto.test.Test.prototype.clearStartAt = function() {
  this.setStartAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.test.Test.prototype.hasStartAt = function() {
  return jspb.Message.getField(this, 14) != null;
};


/**
 * optional google.protobuf.Timestamp end_at = 15;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.test.Test.prototype.getEndAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 15));
};


/** @param {?proto.google.protobuf.Timestamp|undefined} value */
proto.test.Test.prototype.setEndAt = function(value) {
  jspb.Message.setWrapperField(this, 15, value);
};


proto.test.Test.prototype.clearEndAt = function() {
  this.setEndAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.test.Test.prototype.hasEndAt = function() {
  return jspb.Message.getField(this, 15) != null;
};


/**
 * optional google.protobuf.Timestamp closed_at = 16;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.test.Test.prototype.getClosedAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 16));
};


/** @param {?proto.google.protobuf.Timestamp|undefined} value */
proto.test.Test.prototype.setClosedAt = function(value) {
  jspb.Message.setWrapperField(this, 16, value);
};


proto.test.Test.prototype.clearClosedAt = function() {
  this.setClosedAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.test.Test.prototype.hasClosedAt = function() {
  return jspb.Message.getField(this, 16) != null;
};


/**
 * optional google.protobuf.Timestamp public_exposed_at = 17;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.test.Test.prototype.getPublicExposedAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 17));
};


/** @param {?proto.google.protobuf.Timestamp|undefined} value */
proto.test.Test.prototype.setPublicExposedAt = function(value) {
  jspb.Message.setWrapperField(this, 17, value);
};


proto.test.Test.prototype.clearPublicExposedAt = function() {
  this.setPublicExposedAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.test.Test.prototype.hasPublicExposedAt = function() {
  return jspb.Message.getField(this, 17) != null;
};


/**
 * repeated TestScore scores = 18;
 * @return {!Array<!proto.test.TestScore>}
 */
proto.test.Test.prototype.getScoresList = function() {
  return /** @type{!Array<!proto.test.TestScore>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.test.TestScore, 18));
};


/** @param {!Array<!proto.test.TestScore>} value */
proto.test.Test.prototype.setScoresList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 18, value);
};


/**
 * @param {!proto.test.TestScore=} opt_value
 * @param {number=} opt_index
 * @return {!proto.test.TestScore}
 */
proto.test.Test.prototype.addScores = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 18, opt_value, proto.test.TestScore, opt_index);
};


proto.test.Test.prototype.clearScoresList = function() {
  this.setScoresList([]);
};


/**
 * repeated TestExpectedGrade expected_grades = 19;
 * @return {!Array<!proto.test.TestExpectedGrade>}
 */
proto.test.Test.prototype.getExpectedGradesList = function() {
  return /** @type{!Array<!proto.test.TestExpectedGrade>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.test.TestExpectedGrade, 19));
};


/** @param {!Array<!proto.test.TestExpectedGrade>} value */
proto.test.Test.prototype.setExpectedGradesList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 19, value);
};


/**
 * @param {!proto.test.TestExpectedGrade=} opt_value
 * @param {number=} opt_index
 * @return {!proto.test.TestExpectedGrade}
 */
proto.test.Test.prototype.addExpectedGrades = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 19, opt_value, proto.test.TestExpectedGrade, opt_index);
};


proto.test.Test.prototype.clearExpectedGradesList = function() {
  this.setExpectedGradesList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.test.TestScore = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.test.TestScore, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.test.TestScore.displayName = 'proto.test.TestScore';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.test.TestScore.prototype.toObject = function(opt_includeInstance) {
  return proto.test.TestScore.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.test.TestScore} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.test.TestScore.toObject = function(includeInstance, msg) {
  var f, obj = {
    student: (f = msg.getStudent()) && class_class_message_pb.ClassParticipant.toObject(includeInstance, f),
    rank: jspb.Message.getFieldWithDefault(msg, 2, 0),
    score: +jspb.Message.getFieldWithDefault(msg, 3, 0.0),
    standardScore: +jspb.Message.getFieldWithDefault(msg, 4, 0.0),
    percentage: +jspb.Message.getFieldWithDefault(msg, 5, 0.0),
    participated: jspb.Message.getFieldWithDefault(msg, 6, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.test.TestScore}
 */
proto.test.TestScore.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.test.TestScore;
  return proto.test.TestScore.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.test.TestScore} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.test.TestScore}
 */
proto.test.TestScore.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new class_class_message_pb.ClassParticipant;
      reader.readMessage(value,class_class_message_pb.ClassParticipant.deserializeBinaryFromReader);
      msg.setStudent(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setRank(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setScore(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setStandardScore(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setPercentage(value);
      break;
    case 6:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setParticipated(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.test.TestScore.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.test.TestScore.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.test.TestScore} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.test.TestScore.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getStudent();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      class_class_message_pb.ClassParticipant.serializeBinaryToWriter
    );
  }
  f = message.getRank();
  if (f !== 0) {
    writer.writeInt64(
      2,
      f
    );
  }
  f = message.getScore();
  if (f !== 0.0) {
    writer.writeDouble(
      3,
      f
    );
  }
  f = message.getStandardScore();
  if (f !== 0.0) {
    writer.writeDouble(
      4,
      f
    );
  }
  f = message.getPercentage();
  if (f !== 0.0) {
    writer.writeDouble(
      5,
      f
    );
  }
  f = message.getParticipated();
  if (f) {
    writer.writeBool(
      6,
      f
    );
  }
};


/**
 * optional class.ClassParticipant student = 1;
 * @return {?proto.class.ClassParticipant}
 */
proto.test.TestScore.prototype.getStudent = function() {
  return /** @type{?proto.class.ClassParticipant} */ (
    jspb.Message.getWrapperField(this, class_class_message_pb.ClassParticipant, 1));
};


/** @param {?proto.class.ClassParticipant|undefined} value */
proto.test.TestScore.prototype.setStudent = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.test.TestScore.prototype.clearStudent = function() {
  this.setStudent(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.test.TestScore.prototype.hasStudent = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional int64 rank = 2;
 * @return {number}
 */
proto.test.TestScore.prototype.getRank = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.test.TestScore.prototype.setRank = function(value) {
  jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional double score = 3;
 * @return {number}
 */
proto.test.TestScore.prototype.getScore = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 3, 0.0));
};


/** @param {number} value */
proto.test.TestScore.prototype.setScore = function(value) {
  jspb.Message.setProto3FloatField(this, 3, value);
};


/**
 * optional double standard_score = 4;
 * @return {number}
 */
proto.test.TestScore.prototype.getStandardScore = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 4, 0.0));
};


/** @param {number} value */
proto.test.TestScore.prototype.setStandardScore = function(value) {
  jspb.Message.setProto3FloatField(this, 4, value);
};


/**
 * optional double percentage = 5;
 * @return {number}
 */
proto.test.TestScore.prototype.getPercentage = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 5, 0.0));
};


/** @param {number} value */
proto.test.TestScore.prototype.setPercentage = function(value) {
  jspb.Message.setProto3FloatField(this, 5, value);
};


/**
 * optional bool participated = 6;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.test.TestScore.prototype.getParticipated = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 6, false));
};


/** @param {boolean} value */
proto.test.TestScore.prototype.setParticipated = function(value) {
  jspb.Message.setProto3BooleanField(this, 6, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.test.OverallTestScore = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.test.OverallTestScore, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.test.OverallTestScore.displayName = 'proto.test.OverallTestScore';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.test.OverallTestScore.prototype.toObject = function(opt_includeInstance) {
  return proto.test.OverallTestScore.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.test.OverallTestScore} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.test.OverallTestScore.toObject = function(includeInstance, msg) {
  var f, obj = {
    test: (f = msg.getTest()) && proto.test.Test.toObject(includeInstance, f),
    student: (f = msg.getStudent()) && class_class_message_pb.ClassParticipant.toObject(includeInstance, f),
    overallRank: jspb.Message.getFieldWithDefault(msg, 3, 0),
    overallAverageScore: +jspb.Message.getFieldWithDefault(msg, 4, 0.0),
    overallAverageStandardScore: +jspb.Message.getFieldWithDefault(msg, 5, 0.0),
    overallPercentage: +jspb.Message.getFieldWithDefault(msg, 6, 0.0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.test.OverallTestScore}
 */
proto.test.OverallTestScore.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.test.OverallTestScore;
  return proto.test.OverallTestScore.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.test.OverallTestScore} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.test.OverallTestScore}
 */
proto.test.OverallTestScore.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.test.Test;
      reader.readMessage(value,proto.test.Test.deserializeBinaryFromReader);
      msg.setTest(value);
      break;
    case 2:
      var value = new class_class_message_pb.ClassParticipant;
      reader.readMessage(value,class_class_message_pb.ClassParticipant.deserializeBinaryFromReader);
      msg.setStudent(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setOverallRank(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setOverallAverageScore(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setOverallAverageStandardScore(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setOverallPercentage(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.test.OverallTestScore.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.test.OverallTestScore.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.test.OverallTestScore} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.test.OverallTestScore.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTest();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.test.Test.serializeBinaryToWriter
    );
  }
  f = message.getStudent();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      class_class_message_pb.ClassParticipant.serializeBinaryToWriter
    );
  }
  f = message.getOverallRank();
  if (f !== 0) {
    writer.writeInt64(
      3,
      f
    );
  }
  f = message.getOverallAverageScore();
  if (f !== 0.0) {
    writer.writeDouble(
      4,
      f
    );
  }
  f = message.getOverallAverageStandardScore();
  if (f !== 0.0) {
    writer.writeDouble(
      5,
      f
    );
  }
  f = message.getOverallPercentage();
  if (f !== 0.0) {
    writer.writeDouble(
      6,
      f
    );
  }
};


/**
 * optional Test test = 1;
 * @return {?proto.test.Test}
 */
proto.test.OverallTestScore.prototype.getTest = function() {
  return /** @type{?proto.test.Test} */ (
    jspb.Message.getWrapperField(this, proto.test.Test, 1));
};


/** @param {?proto.test.Test|undefined} value */
proto.test.OverallTestScore.prototype.setTest = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.test.OverallTestScore.prototype.clearTest = function() {
  this.setTest(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.test.OverallTestScore.prototype.hasTest = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional class.ClassParticipant student = 2;
 * @return {?proto.class.ClassParticipant}
 */
proto.test.OverallTestScore.prototype.getStudent = function() {
  return /** @type{?proto.class.ClassParticipant} */ (
    jspb.Message.getWrapperField(this, class_class_message_pb.ClassParticipant, 2));
};


/** @param {?proto.class.ClassParticipant|undefined} value */
proto.test.OverallTestScore.prototype.setStudent = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.test.OverallTestScore.prototype.clearStudent = function() {
  this.setStudent(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.test.OverallTestScore.prototype.hasStudent = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional int64 overall_rank = 3;
 * @return {number}
 */
proto.test.OverallTestScore.prototype.getOverallRank = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {number} value */
proto.test.OverallTestScore.prototype.setOverallRank = function(value) {
  jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional double overall_average_score = 4;
 * @return {number}
 */
proto.test.OverallTestScore.prototype.getOverallAverageScore = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 4, 0.0));
};


/** @param {number} value */
proto.test.OverallTestScore.prototype.setOverallAverageScore = function(value) {
  jspb.Message.setProto3FloatField(this, 4, value);
};


/**
 * optional double overall_average_standard_score = 5;
 * @return {number}
 */
proto.test.OverallTestScore.prototype.getOverallAverageStandardScore = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 5, 0.0));
};


/** @param {number} value */
proto.test.OverallTestScore.prototype.setOverallAverageStandardScore = function(value) {
  jspb.Message.setProto3FloatField(this, 5, value);
};


/**
 * optional double overall_percentage = 6;
 * @return {number}
 */
proto.test.OverallTestScore.prototype.getOverallPercentage = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 6, 0.0));
};


/** @param {number} value */
proto.test.OverallTestScore.prototype.setOverallPercentage = function(value) {
  jspb.Message.setProto3FloatField(this, 6, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.test.TestExpectedGrade = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.test.TestExpectedGrade, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.test.TestExpectedGrade.displayName = 'proto.test.TestExpectedGrade';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.test.TestExpectedGrade.prototype.toObject = function(opt_includeInstance) {
  return proto.test.TestExpectedGrade.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.test.TestExpectedGrade} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.test.TestExpectedGrade.toObject = function(includeInstance, msg) {
  var f, obj = {
    standardScore: +jspb.Message.getFieldWithDefault(msg, 1, 0.0),
    grade: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.test.TestExpectedGrade}
 */
proto.test.TestExpectedGrade.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.test.TestExpectedGrade;
  return proto.test.TestExpectedGrade.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.test.TestExpectedGrade} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.test.TestExpectedGrade}
 */
proto.test.TestExpectedGrade.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setStandardScore(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setGrade(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.test.TestExpectedGrade.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.test.TestExpectedGrade.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.test.TestExpectedGrade} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.test.TestExpectedGrade.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getStandardScore();
  if (f !== 0.0) {
    writer.writeDouble(
      1,
      f
    );
  }
  f = message.getGrade();
  if (f !== 0) {
    writer.writeInt64(
      2,
      f
    );
  }
};


/**
 * optional double standard_score = 1;
 * @return {number}
 */
proto.test.TestExpectedGrade.prototype.getStandardScore = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 1, 0.0));
};


/** @param {number} value */
proto.test.TestExpectedGrade.prototype.setStandardScore = function(value) {
  jspb.Message.setProto3FloatField(this, 1, value);
};


/**
 * optional int64 grade = 2;
 * @return {number}
 */
proto.test.TestExpectedGrade.prototype.getGrade = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.test.TestExpectedGrade.prototype.setGrade = function(value) {
  jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * @enum {number}
 */
proto.test.ExposeRankType = {
  EXPOSE_RANK_TYPE_UNSPECIFIED: 0,
  EXPOSE_RANK_TYPE_ONLY_SELF: 1,
  EXPOSE_RANK_TYPE_FIRST: 2,
  EXPOSE_RANK_TYPE_SECOND: 3,
  EXPOSE_RANK_TYPE_THIRD: 4,
  EXPOSE_RANK_TYPE_ALL: 5
};

goog.object.extend(exports, proto.test);
