/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
var auth_auth_message_pb = require('../auth/auth_message_pb.js');
var label_label_message_pb = require('../label/label_message_pb.js');
goog.exportSymbol('proto.class.Class', null, global);
goog.exportSymbol('proto.class.ClassParticipant', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.class.Class = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.class.Class.repeatedFields_, null);
};
goog.inherits(proto.class.Class, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.class.Class.displayName = 'proto.class.Class';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.class.Class.repeatedFields_ = [4,12];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.class.Class.prototype.toObject = function(opt_includeInstance) {
  return proto.class.Class.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.class.Class} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.class.Class.toObject = function(includeInstance, msg) {
  var f, obj = {
    uid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    createdAt: (f = msg.getCreatedAt()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    updatedAt: (f = msg.getUpdatedAt()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    teachersList: jspb.Message.toObjectList(msg.getTeachersList(),
    proto.class.ClassParticipant.toObject, includeInstance),
    name: jspb.Message.getFieldWithDefault(msg, 5, ""),
    description: jspb.Message.getFieldWithDefault(msg, 6, ""),
    classLabel: (f = msg.getClassLabel()) && label_label_message_pb.Label.toObject(includeInstance, f),
    startDate: (f = msg.getStartDate()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    endDate: (f = msg.getEndDate()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    closedAt: (f = msg.getClosedAt()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    publicExposedAt: (f = msg.getPublicExposedAt()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    classParticipantsList: jspb.Message.toObjectList(msg.getClassParticipantsList(),
    proto.class.ClassParticipant.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.class.Class}
 */
proto.class.Class.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.class.Class;
  return proto.class.Class.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.class.Class} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.class.Class}
 */
proto.class.Class.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setUid(value);
      break;
    case 2:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setCreatedAt(value);
      break;
    case 3:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setUpdatedAt(value);
      break;
    case 4:
      var value = new proto.class.ClassParticipant;
      reader.readMessage(value,proto.class.ClassParticipant.deserializeBinaryFromReader);
      msg.addTeachers(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescription(value);
      break;
    case 7:
      var value = new label_label_message_pb.Label;
      reader.readMessage(value,label_label_message_pb.Label.deserializeBinaryFromReader);
      msg.setClassLabel(value);
      break;
    case 8:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setStartDate(value);
      break;
    case 9:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setEndDate(value);
      break;
    case 10:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setClosedAt(value);
      break;
    case 11:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setPublicExposedAt(value);
      break;
    case 12:
      var value = new proto.class.ClassParticipant;
      reader.readMessage(value,proto.class.ClassParticipant.deserializeBinaryFromReader);
      msg.addClassParticipants(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.class.Class.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.class.Class.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.class.Class} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.class.Class.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getCreatedAt();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getUpdatedAt();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getTeachersList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      4,
      f,
      proto.class.ClassParticipant.serializeBinaryToWriter
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getDescription();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getClassLabel();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      label_label_message_pb.Label.serializeBinaryToWriter
    );
  }
  f = message.getStartDate();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getEndDate();
  if (f != null) {
    writer.writeMessage(
      9,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getClosedAt();
  if (f != null) {
    writer.writeMessage(
      10,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getPublicExposedAt();
  if (f != null) {
    writer.writeMessage(
      11,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getClassParticipantsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      12,
      f,
      proto.class.ClassParticipant.serializeBinaryToWriter
    );
  }
};


/**
 * optional string uid = 1;
 * @return {string}
 */
proto.class.Class.prototype.getUid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.class.Class.prototype.setUid = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional google.protobuf.Timestamp created_at = 2;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.class.Class.prototype.getCreatedAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 2));
};


/** @param {?proto.google.protobuf.Timestamp|undefined} value */
proto.class.Class.prototype.setCreatedAt = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.class.Class.prototype.clearCreatedAt = function() {
  this.setCreatedAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.class.Class.prototype.hasCreatedAt = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional google.protobuf.Timestamp updated_at = 3;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.class.Class.prototype.getUpdatedAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 3));
};


/** @param {?proto.google.protobuf.Timestamp|undefined} value */
proto.class.Class.prototype.setUpdatedAt = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


proto.class.Class.prototype.clearUpdatedAt = function() {
  this.setUpdatedAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.class.Class.prototype.hasUpdatedAt = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * repeated ClassParticipant teachers = 4;
 * @return {!Array<!proto.class.ClassParticipant>}
 */
proto.class.Class.prototype.getTeachersList = function() {
  return /** @type{!Array<!proto.class.ClassParticipant>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.class.ClassParticipant, 4));
};


/** @param {!Array<!proto.class.ClassParticipant>} value */
proto.class.Class.prototype.setTeachersList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 4, value);
};


/**
 * @param {!proto.class.ClassParticipant=} opt_value
 * @param {number=} opt_index
 * @return {!proto.class.ClassParticipant}
 */
proto.class.Class.prototype.addTeachers = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 4, opt_value, proto.class.ClassParticipant, opt_index);
};


proto.class.Class.prototype.clearTeachersList = function() {
  this.setTeachersList([]);
};


/**
 * optional string name = 5;
 * @return {string}
 */
proto.class.Class.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/** @param {string} value */
proto.class.Class.prototype.setName = function(value) {
  jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string description = 6;
 * @return {string}
 */
proto.class.Class.prototype.getDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/** @param {string} value */
proto.class.Class.prototype.setDescription = function(value) {
  jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional label.Label class_label = 7;
 * @return {?proto.label.Label}
 */
proto.class.Class.prototype.getClassLabel = function() {
  return /** @type{?proto.label.Label} */ (
    jspb.Message.getWrapperField(this, label_label_message_pb.Label, 7));
};


/** @param {?proto.label.Label|undefined} value */
proto.class.Class.prototype.setClassLabel = function(value) {
  jspb.Message.setWrapperField(this, 7, value);
};


proto.class.Class.prototype.clearClassLabel = function() {
  this.setClassLabel(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.class.Class.prototype.hasClassLabel = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional google.protobuf.Timestamp start_date = 8;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.class.Class.prototype.getStartDate = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 8));
};


/** @param {?proto.google.protobuf.Timestamp|undefined} value */
proto.class.Class.prototype.setStartDate = function(value) {
  jspb.Message.setWrapperField(this, 8, value);
};


proto.class.Class.prototype.clearStartDate = function() {
  this.setStartDate(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.class.Class.prototype.hasStartDate = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional google.protobuf.Timestamp end_date = 9;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.class.Class.prototype.getEndDate = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 9));
};


/** @param {?proto.google.protobuf.Timestamp|undefined} value */
proto.class.Class.prototype.setEndDate = function(value) {
  jspb.Message.setWrapperField(this, 9, value);
};


proto.class.Class.prototype.clearEndDate = function() {
  this.setEndDate(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.class.Class.prototype.hasEndDate = function() {
  return jspb.Message.getField(this, 9) != null;
};


/**
 * optional google.protobuf.Timestamp closed_at = 10;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.class.Class.prototype.getClosedAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 10));
};


/** @param {?proto.google.protobuf.Timestamp|undefined} value */
proto.class.Class.prototype.setClosedAt = function(value) {
  jspb.Message.setWrapperField(this, 10, value);
};


proto.class.Class.prototype.clearClosedAt = function() {
  this.setClosedAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.class.Class.prototype.hasClosedAt = function() {
  return jspb.Message.getField(this, 10) != null;
};


/**
 * optional google.protobuf.Timestamp public_exposed_at = 11;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.class.Class.prototype.getPublicExposedAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 11));
};


/** @param {?proto.google.protobuf.Timestamp|undefined} value */
proto.class.Class.prototype.setPublicExposedAt = function(value) {
  jspb.Message.setWrapperField(this, 11, value);
};


proto.class.Class.prototype.clearPublicExposedAt = function() {
  this.setPublicExposedAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.class.Class.prototype.hasPublicExposedAt = function() {
  return jspb.Message.getField(this, 11) != null;
};


/**
 * repeated ClassParticipant class_participants = 12;
 * @return {!Array<!proto.class.ClassParticipant>}
 */
proto.class.Class.prototype.getClassParticipantsList = function() {
  return /** @type{!Array<!proto.class.ClassParticipant>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.class.ClassParticipant, 12));
};


/** @param {!Array<!proto.class.ClassParticipant>} value */
proto.class.Class.prototype.setClassParticipantsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 12, value);
};


/**
 * @param {!proto.class.ClassParticipant=} opt_value
 * @param {number=} opt_index
 * @return {!proto.class.ClassParticipant}
 */
proto.class.Class.prototype.addClassParticipants = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 12, opt_value, proto.class.ClassParticipant, opt_index);
};


proto.class.Class.prototype.clearClassParticipantsList = function() {
  this.setClassParticipantsList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.class.ClassParticipant = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.class.ClassParticipant, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.class.ClassParticipant.displayName = 'proto.class.ClassParticipant';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.class.ClassParticipant.prototype.toObject = function(opt_includeInstance) {
  return proto.class.ClassParticipant.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.class.ClassParticipant} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.class.ClassParticipant.toObject = function(includeInstance, msg) {
  var f, obj = {
    userUid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    authLevel: jspb.Message.getFieldWithDefault(msg, 2, 0),
    name: jspb.Message.getFieldWithDefault(msg, 3, ""),
    userLabel: (f = msg.getUserLabel()) && label_label_message_pb.Label.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.class.ClassParticipant}
 */
proto.class.ClassParticipant.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.class.ClassParticipant;
  return proto.class.ClassParticipant.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.class.ClassParticipant} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.class.ClassParticipant}
 */
proto.class.ClassParticipant.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setUserUid(value);
      break;
    case 2:
      var value = /** @type {!proto.auth.Level} */ (reader.readEnum());
      msg.setAuthLevel(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 4:
      var value = new label_label_message_pb.Label;
      reader.readMessage(value,label_label_message_pb.Label.deserializeBinaryFromReader);
      msg.setUserLabel(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.class.ClassParticipant.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.class.ClassParticipant.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.class.ClassParticipant} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.class.ClassParticipant.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUserUid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getAuthLevel();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getUserLabel();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      label_label_message_pb.Label.serializeBinaryToWriter
    );
  }
};


/**
 * optional string user_uid = 1;
 * @return {string}
 */
proto.class.ClassParticipant.prototype.getUserUid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.class.ClassParticipant.prototype.setUserUid = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional auth.Level auth_level = 2;
 * @return {!proto.auth.Level}
 */
proto.class.ClassParticipant.prototype.getAuthLevel = function() {
  return /** @type {!proto.auth.Level} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {!proto.auth.Level} value */
proto.class.ClassParticipant.prototype.setAuthLevel = function(value) {
  jspb.Message.setProto3EnumField(this, 2, value);
};


/**
 * optional string name = 3;
 * @return {string}
 */
proto.class.ClassParticipant.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.class.ClassParticipant.prototype.setName = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional label.Label user_label = 4;
 * @return {?proto.label.Label}
 */
proto.class.ClassParticipant.prototype.getUserLabel = function() {
  return /** @type{?proto.label.Label} */ (
    jspb.Message.getWrapperField(this, label_label_message_pb.Label, 4));
};


/** @param {?proto.label.Label|undefined} value */
proto.class.ClassParticipant.prototype.setUserLabel = function(value) {
  jspb.Message.setWrapperField(this, 4, value);
};


proto.class.ClassParticipant.prototype.clearUserLabel = function() {
  this.setUserLabel(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.class.ClassParticipant.prototype.hasUserLabel = function() {
  return jspb.Message.getField(this, 4) != null;
};


goog.object.extend(exports, proto.class);
